p8105_hw6_mc5503
================
mc5503
2023-11-27

## Problem 2

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

    ## using cached file: C:\Users\24233\AppData\Local/R/cache/R/rnoaa/noaa_ghcnd/USW00094728.dly

    ## date created (size, mb): 2023-11-26 19:27:44.573019 (8.561)

    ## file min/max dates: 1869-01-01 / 2023-11-30

``` r
boot_sample=function(df) {
  sample_frac(df, replace = TRUE)
}
boot_straps = 
  tibble(strap_number = 1:5000) |> 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = weather_df))
  )
```

``` r
bootstrap_results = 
  boot_straps |> 
  mutate(
    models = map(strap_sample, \(df) lm(tmax ~ tmin+prcp, data = df) ),
    results1 = map(models, broom::tidy),
    results2=map(models,broom::glance))|> 
  select(-strap_sample, -models) |> 
  unnest(results1,results2)
```

``` r
results=bootstrap_results |> 
  select(strap_number,term,estimate,r.squared)|>
  pivot_wider(names_from = term,
              values_from = estimate)|>
  mutate(quantity2=log(tmin*prcp))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `quantity2 = log(tmin * prcp)`.
    ## Caused by warning in `log()`:
    ## ! 产生了NaNs

``` r
results|>ggplot(aes(x=r.squared))+geom_histogram()
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](p8105_hw6_mc5503_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

``` r
results|>ggplot(aes(x=quantity2))+geom_histogram()+labs(x="log(beta1*beta2)")
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

    ## Warning: Removed 3413 rows containing non-finite values (`stat_bin()`).

![](p8105_hw6_mc5503_files/figure-gfm/unnamed-chunk-4-2.png)<!-- -->

``` r
results|>pull(r.squared)|>quantile(0.025)
```

    ##      2.5% 
    ## 0.8893403

``` r
results|>pull(r.squared)|>quantile(0.975)
```

    ##     97.5% 
    ## 0.9405245

``` r
results|>pull(quantity2)|>na.omit()|>quantile(0.025)
```

    ##      2.5% 
    ## -8.860503

``` r
results|>pull(quantity2)|>na.omit()|>quantile(0.975)
```

    ##     97.5% 
    ## -4.565257

The confidence interval for the first quantity is \[0.8893403,
0.9405245\], and the confidence interval for the second quantity is
\[-8.8605027, -4.5652574\]. NAs are omitted.

## Problem 3

``` r
data3=read.csv("data/birthweight.csv")|>
  mutate(babysex=recode(babysex,"1"="male","2"="female"),
         mrace=recode(mrace,"1" = "White", "2" = "Black", "3" = "Asian", '4' = "Puerto Rican", "8" = "Other"),
         frace=recode(frace,"1" = "White", "2" = "Black", "3" = "Asian", '4' = "Puerto Rican", '8' = "Other", "9" ="Unknown"))|>
  drop_na()
```

### fit the model

It’s reasonable to think that child’s weight is directly relative to
mom’s body index and health condition, gestational age and the the
income, so I include all of those variables into the model. Then delete
those variables which are not significant.

``` r
fit=lm(bwt~fincome+gaweeks+malform+momage+mrace+ppbmi+smoken+wtgain,data3)
summary(fit)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ fincome + gaweeks + malform + momage + mrace + 
    ##     ppbmi + smoken + wtgain, data = data3)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1755.90  -264.45     6.63   278.81  1692.27 
    ## 
    ## Coefficients:
    ##                    Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)        345.6477   118.4755   2.917  0.00355 ** 
    ## fincome              0.5188     0.2807   1.848  0.06469 .  
    ## gaweeks             53.3011     2.1346  24.970  < 2e-16 ***
    ## malform            -45.8402   111.2143  -0.412  0.68023    
    ## momage               2.5781     1.8757   1.375  0.16935    
    ## mraceBlack        -160.0428    67.7413  -2.363  0.01819 *  
    ## mracePuerto Rican  -57.5789    72.1845  -0.798  0.42511    
    ## mraceWhite         122.0203    67.1192   1.818  0.06914 .  
    ## ppbmi               19.9625     2.0890   9.556  < 2e-16 ***
    ## smoken             -11.3714     0.9112 -12.480  < 2e-16 ***
    ## wtgain              10.0548     0.6098  16.488  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 429.3 on 4331 degrees of freedom
    ## Multiple R-squared:  0.2991, Adjusted R-squared:  0.2975 
    ## F-statistic: 184.8 on 10 and 4331 DF,  p-value: < 2.2e-16

``` r
fit=lm(bwt~fincome+gaweeks+mrace+ppbmi+smoken+wtgain,data3)
summary(fit)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ fincome + gaweeks + mrace + ppbmi + smoken + 
    ##     wtgain, data = data3)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1748.73  -265.23     6.85   277.31  1698.49 
    ## 
    ## Coefficients:
    ##                    Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)        396.2449   112.5375   3.521 0.000434 ***
    ## fincome              0.6046     0.2740   2.207 0.027379 *  
    ## gaweeks             53.4752     2.1312  25.092  < 2e-16 ***
    ## mraceBlack        -176.8326    66.6348  -2.654 0.007989 ** 
    ## mracePuerto Rican  -72.0634    71.4059  -1.009 0.312931    
    ## mraceWhite         110.3346    66.5935   1.657 0.097625 .  
    ## ppbmi               20.2781     2.0760   9.768  < 2e-16 ***
    ## smoken             -11.3800     0.9109 -12.494  < 2e-16 ***
    ## wtgain               9.9700     0.6069  16.427  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 429.3 on 4333 degrees of freedom
    ## Multiple R-squared:  0.2988, Adjusted R-squared:  0.2975 
    ## F-statistic: 230.8 on 8 and 4333 DF,  p-value: < 2.2e-16

``` r
results_data=modelr::add_residuals(data3, fit)|>modelr::add_predictions(fit)

results_data|>ggplot(aes(x=pred,y=resid))+geom_point()
```

![](p8105_hw6_mc5503_files/figure-gfm/unnamed-chunk-8-1.png)<!-- -->

There is no heteroscedasticity according to the graph.

``` r
fit1=lm(bwt~gaweeks+blength,data3)
summary(fit1)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ gaweeks + blength, data = data3)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -1709.6  -215.4   -11.4   208.2  4188.8 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -4347.667     97.958  -44.38   <2e-16 ***
    ## gaweeks        27.047      1.718   15.74   <2e-16 ***
    ## blength       128.556      1.990   64.60   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 333.2 on 4339 degrees of freedom
    ## Multiple R-squared:  0.5769, Adjusted R-squared:  0.5767 
    ## F-statistic:  2958 on 2 and 4339 DF,  p-value: < 2.2e-16

``` r
fit2=lm(bwt~bhead*blength*babysex,data3)
summary(fit2)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ bhead * blength * babysex, data = data3)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1132.99  -190.42   -10.33   178.63  2617.96 
    ## 
    ## Coefficients:
    ##                             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)                -801.9487  1102.3077  -0.728 0.466948    
    ## bhead                       -16.5975    34.0916  -0.487 0.626388    
    ## blength                     -21.6460    23.3720  -0.926 0.354421    
    ## babysexmale               -6374.8684  1677.7669  -3.800 0.000147 ***
    ## bhead:blength                 3.3244     0.7126   4.666 3.17e-06 ***
    ## bhead:babysexmale           198.3932    51.0917   3.883 0.000105 ***
    ## blength:babysexmale         123.7729    35.1185   3.524 0.000429 ***
    ## bhead:blength:babysexmale    -3.8781     1.0566  -3.670 0.000245 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 287.7 on 4334 degrees of freedom
    ## Multiple R-squared:  0.6849, Adjusted R-squared:  0.6844 
    ## F-statistic:  1346 on 7 and 4334 DF,  p-value: < 2.2e-16

``` r
cv_df = 
  crossv_mc(data3, 100) 

cv_df =
  cv_df |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

``` r
cv_df = 
  cv_df |> 
  mutate(
    mod1  = map(train, \(df) lm(bwt~fincome+gaweeks+mrace+ppbmi+smoken+wtgain,df)),
    mod2  = map(train, \(df) lm(bwt~gaweeks+blength,df)),
    mod3  = map(train, \(df) lm(bwt~bhead*blength*babysex,df))) |> 
  mutate(
    rmse_mod1 = map2_dbl(mod1, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_mod2 = map2_dbl(mod2, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_mod3 = map2_dbl(mod3, test, \(mod, df) rmse(model = mod, data = df)))
```

``` r
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

![](p8105_hw6_mc5503_files/figure-gfm/unnamed-chunk-12-1.png)<!-- -->

Since my model does not contain baby’s body index, the prediction is not
so efficient as two others. Model using head circumference, length, sex,
and all interactions is the optimal one.
