---
title: "p8105_hw6_mc5503"
author: "mc5503"
date: '2023-11-27'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
```

## Problem 2
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
boot_sample=function(df) {
  sample_frac(df, replace = TRUE)
}
boot_straps = 
  tibble(strap_number = 1:5000) |> 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = weather_df))
  )
```

```{r,warning=FALSE}
bootstrap_results = 
  boot_straps |> 
  mutate(
    models = map(strap_sample, \(df) lm(tmax ~ tmin+prcp, data = df) ),
    results1 = map(models, broom::tidy),
    results2=map(models,broom::glance))|> 
  select(-strap_sample, -models) |> 
  unnest(results1,results2)
```

```{r}
results=bootstrap_results |> 
  select(strap_number,term,estimate,r.squared)|>
  pivot_wider(names_from = term,
              values_from = estimate)|>
  mutate(quantity2=log(tmin*prcp))

results|>ggplot(aes(x=r.squared))+geom_histogram()

results|>ggplot(aes(x=quantity2))+geom_histogram()+labs(x="log(beta1*beta2)")
```

```{r}
results|>pull(r.squared)|>quantile(0.025)
results|>pull(r.squared)|>quantile(0.975)

results|>pull(quantity2)|>na.omit()|>quantile(0.025)
results|>pull(quantity2)|>na.omit()|>quantile(0.975)
```

The confidence interval for the first quantity is [`r c(results|>pull(r.squared)|>quantile(0.025),results|>pull(r.squared)|>quantile(0.975))`], and the confidence interval for the second quantity is [`r c(results|>pull(quantity2)|>na.omit()|>quantile(0.025),results|>pull(quantity2)|>na.omit()|>quantile(0.975))`]. NAs are omitted.
